app = "your-bot-name"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

# Run as a background service
[services]
  [[services.run]]
    command = "python main.py"
    auto_stop_machines = false
    auto_start_machines = true
    min_machines_running = 1

# Persistent storage
[[mounts]]
  source = "bot_data"
  destination = "/app/data" 