app = "teletherapist-bot"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = [
    "gcr.io/paketo-buildpacks/python",
    "gcr.io/paketo-buildpacks/apt"
  ]

[build.apt]
  packages = ["ffmpeg"]

[env]
  PYTHONUNBUFFERED = "1"
  PORT = "8080"

# Specify this is a worker app
[experimental]
  cmd = ["poetry", "run", "python", "main.py"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "bot_data"
  destination = "/app/data" 