app = "your-bot-name"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

# Remove the default HTTP service since this is a bot
[processes]
  bot = "python main.py"

# Configure persistent volume for SQLite
[mounts]
  source = "bot_data"
  destination = "/app/data"

# Disable the default HTTP service
[http_service]
  internal_port = 0
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1 