app = "teletherapist-bot"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

# Specify this is a worker app
[experimental]
  cmd = ["python", "main.py"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "bot_data"
  destination = "/app/data" 