app = "teletherapist-bot"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

# Simple service definition
[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 8080

# Persistent storage
[[mounts]]
  source = "bot_data"
  destination = "/app/data" 